using System.Globalization;

namespace CodexAccountManager;

public sealed partial class CodexCliService
{
    private static bool IsLegacyDisabledCompactionLimit(string line)
    {
        if (!IsTopLevelModelAutoCompactTokenLimitLine(line.Trim())) return false;
        var value = line[(line.IndexOf('=') + 1)..].Split('#', 2)[0].Trim().Replace("_", "");
        return long.TryParse(value, NumberStyles.Integer, CultureInfo.InvariantCulture, out var limit) &&
               limit == LegacyDisabledAutoCompactTokenLimit;
    }

    // Use Codex's stable native v2 protocol. Do not fake encrypted compaction items,
    // drop the transcript, switch credentials, or inflate the model context window.
    // Only remove the exact obsolete value previously generated by this manager.
    private static string RepairManagedCompactionSettings(string config)
    {
        var lines = config.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n');
        var inTopLevel = true;
        var kept = new List<string>();
        foreach (var line in lines)
        {
            if (line.TrimStart().StartsWith("[", StringComparison.Ordinal)) inTopLevel = false;
            if (inTopLevel && IsLegacyDisabledCompactionLimit(line)) continue;
            kept.Add(line);
        }
        return UpsertFeatureFlag(string.Join(Environment.NewLine, kept), "remote_compaction_v2", true);
    }

    internal int SyncManagedCompactionSettings()
    {
        var homes = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var account in new AccountStore().LoadAccounts().Where(a => a.IsCompatibleApi || a.IsAccessToken))
        {
            homes.Add(account.CodexHome);
            if (IsSharedActiveAccount(account)) homes.Add(GetDefaultCodexHome());
        }
        var updated = 0;
        foreach (var home in homes)
        {
            var path = Path.Combine(home, ConfigFileName);
            if (!File.Exists(path)) continue;
            var original = File.ReadAllText(path);
            var projected = RepairManagedCompactionSettings(original);
            if (projected == original) continue;
            var backup = Path.Combine(home, "backups", "native-compaction-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(backup);
            BackupFileIfPresent(path, backup);
            WriteTextAtomically(path, projected);
            updated++;
        }
        return updated;
    }

    internal static void ValidateNativeCompactionSettings()
    {
        const string legacy = "model = \"gpt-6-astra\"\nmodel_auto_compact_token_limit = 1_000_000_000 # old manager\n" +
            "[features]\nremote_compaction_v2 = false\n" +
            "[model_providers.test]\nexperimental_bearer_token = \"test-only\"\nbase_url = \"https://example.test\"\n";
        var repaired = RepairManagedCompactionSettings(legacy);
        var custom = "model_auto_compact_token_limit = 180000\n[features]\nremote_compaction_v2 = false\n";
        var account = new AccountRecord { AuthKind = AccountAuthKind.CompatibleApi, ApiModel = "gpt-6-astra", ApiBaseUrl = "https://example.test" };
        foreach (var config in new[] { repaired, ProjectCompatibleApiConfigText(legacy, account),
                     ProjectWindowsClientConfigText(legacy), AccountStore.BuildAccessTokenConfig(), AccountStore.BuildCompatibleApiConfig(account) })
        {
            if (!FeatureFlagMatches(config, "remote_compaction_v2", true) || config.Contains("1000000000") || config.Contains("1_000_000_000"))
                throw new InvalidOperationException("Managed launch path disabled native compaction.");
        }
        if (RepairManagedCompactionSettings(repaired) != repaired ||
            !repaired.Contains("experimental_bearer_token = \"test-only\"") ||
            !repaired.Contains("base_url = \"https://example.test\"") ||
            !RepairManagedCompactionSettings(custom).Contains("model_auto_compact_token_limit = 180000") ||
            !ProjectCompatibleApiConfigText(custom, account).Contains("model_auto_compact_token_limit = 180000") ||
            !ProjectWindowsClientConfigText(custom).Contains("model_auto_compact_token_limit = 180000"))
            throw new InvalidOperationException("Compaction migration changed unrelated credentials, routes, or custom thresholds.");
    }
}
